PROCESS BEFORE OUTPUT.

MODULE %_INIT_PBO.

MODULE %_PBO_REPORT.

MODULE %_PF_STATUS.

MODULE %_END_OF_PBO.

PROCESS AFTER INPUT.

  MODULE %_BACK AT EXIT-COMMAND.

  MODULE %_INIT_PAI.

CHAIN.
  FIELD P_SMW0  .
  FIELD P_FILE  .
    MODULE %_RADIOBUTTON_GROUP_RAD2                          .
ENDCHAIN.

FIELD !P_OBJID MODULE %_P_OBJID .

FIELD !P_FPATH MODULE %_P_FPATH .


CHAIN.
  FIELD P_SMW0  .
  FIELD P_FILE  .
  FIELD P_OBJID .
  FIELD P_FPATH .
    MODULE %_BLOCK_1000000.
ENDCHAIN.

CHAIN.
  FIELD P_NORMAL.
  FIELD P_OTHER .
    MODULE %_RADIOBUTTON_GROUP_RAD1                          .
ENDCHAIN.


CHAIN.
  FIELD P_NORMAL.
  FIELD P_OTHER .
    MODULE %_BLOCK_1000006.
ENDCHAIN.

CHAIN.
  FIELD P_SMW0  .
  FIELD P_FILE  .
  FIELD P_OBJID .
  FIELD P_FPATH .
  FIELD P_NORMAL.
  FIELD P_OTHER .
  MODULE %_END_OF_SCREEN.
  MODULE %_OK_CODE_1000.
ENDCHAIN.

PROCESS ON VALUE-REQUEST.
  FIELD P_FPATH MODULE %_P_FPATH_VAL .